apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mass-recruit-hub.fullname" . }}-env
  labels:
    {{- include "mass-recruit-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  LLM_API_KEY: ""
  MLFLOW_TRACKING_USERNAME: ""
  MLFLOW_TRACKING_PASSWORD: ""
