global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yaml"

scrape_configs:
  - job_name: 'mass-recruit-hub'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
